:bug: Pin resource-factory to 1.2.0 due to classloader bug
1.3.0 and 1.3.1 fail :mainResourceFactory with NoClassDefFoundError on
net.kyori.option.OptionStateImpl due to two classloaders loading
kyori-option (likely indra/jtoml-configurate bumps in 1.3.0).